### ISSUE TITLE
自动重新计时不太完善

### ISSUE THREAD

**Issue by TomJohnyoan** [Luxuriagk/LogisticManager#1]
勾选“自动重新计时”后有两个后勤在结束后重置了计时，但是需要手动启动。这对与一个需要长期跑同一套后勤方案不间断的咸仓鼠来说很不友好。
![image](https://user-images.githubusercontent.com/51290732/58761788-6ba52480-857a-11e9-9d04-80d2ef6fec83.png)

**Comment by LuxuriaGK** [comment]
v2.0修复了
